apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: ai-kickstarts-pipeline
spec:
  workspaces:
    - name: shared-workspace
    - name: docker-config
  params:
    - name: git-url
      type: string
      description: The git repository URL
      default: https://github.com/erwangranger/AI-Kickstart-rendering.git
    - name: git-revision
      type: string
      description: The git revision to build
      default: hostonopenshift
    - name: image-name
      type: string
      description: The name of the image to build
      default: ai-kickstarts-app
    - name: image-tag
      type: string
      description: The tag of the image to build
      default: latest
    - name: registry-url
      type: string
      description: The OpenShift registry URL
      default: image-registry.openshift-image-registry.svc:5000
    - name: registry-namespace
      type: string
      description: The OpenShift project/namespace
      default: ai-kickstarts
  tasks:
    - name: fetch-repository
      taskRef:
        name: git-clone
      workspaces:
        - name: output
          workspace: shared-workspace
      params:
        - name: url
          value: $(params.git-url)
        - name: revision
          value: $(params.git-revision)
        - name: submodules
          value: "true"
        - name: depth
          value: "1"

    - name: create-imagestream
      taskRef:
        name: openshift-client
      params:
        - name: SCRIPT
          value: |
            #!/usr/bin/env bash
            oc get imagestream $(params.image-name) -n $(params.registry-namespace) || \
            oc create imagestream $(params.image-name) -n $(params.registry-namespace)
      runAfter:
        - fetch-repository

    - name: build-and-push
      taskRef:
        name: buildah
      runAfter:
        - create-imagestream
      workspaces:
        - name: source
          workspace: shared-workspace
        - name: dockerconfig
          workspace: docker-config
      params:
        - name: IMAGE
          value: $(params.registry-url)/$(params.registry-namespace)/$(params.image-name):$(params.image-tag)
        - name: DOCKERFILE
          value: Containerfile
        - name: CONTEXT
          value: .
        - name: BUILDAH_ARGS
          value: "--format=oci"
        - name: TLSVERIFY
          value: "false"
        - name: STORAGE_DRIVER
          value: "vfs"

    - name: deploy
      taskRef:
        name: openshift-client
      runAfter:
        - build-and-push
      params:
        - name: SCRIPT
          value: |
            #!/usr/bin/env bash
            # Update the deployment with the new image
            oc set image deployment/ai-kickstarts-app ai-kickstarts-app=$(params.registry-url)/$(params.registry-namespace)/$(params.image-name):$(params.image-tag) -n $(params.registry-namespace)
            # Wait for the deployment to roll out
            oc rollout status deployment/ai-kickstarts-app -n $(params.registry-namespace) --timeout=300s