apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: ai-kickstarts-app
  labels:
    app: ai-kickstarts-app
spec:
  source:
    git:
      uri: https://github.com/erwangranger/AI-Kickstart-rendering.git
      ref: hostonopenshift
    contextDir: .
  strategy:
    type: Docker
    dockerStrategy:
      dockerfilePath: Containerfile
      buildArgs:
      - name: GH_TOKEN
        valueFrom:
          secretKeyRef:
            name: github-token
            key: token
  output:
    to:
      kind: ImageStreamTag
      name: ai-kickstarts-app:latest
  triggers:
  - type: ConfigChange
  - type: ImageChange
  resources:
    requests:
      memory: "512Mi"
      cpu: "500m"
    limits:
      memory: "1Gi"
      cpu: "1000m"