name: Deploy to GitHub Pages (Per-Branch Previews)

on:
  push:
    branches:
      - main
      - '*' # Trigger on pushes to all branches
  pull_request:
    types: [opened, synchronize, reopened] # Trigger on PR creation, updates, and reopening

# Explicitly grant permissions to the GITHUB_TOKEN for GitHub Pages deployment
permissions:
  contents: write # Needed to push to the gh-pages branch (for the build artifact)
  pages: write    # Needed for GitHub Pages deployment
  id-token: write # Needed for OpenID Connect (if using, generally good practice for GH Pages)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Action to check out your repository code

      - name: Set up Node.js
        uses: actions/setup-node@v3 # Action to set up Node.js environment
        with:
          node-version: '18' # Specify Node.js version

      # Step to determine the base URL (PUBLIC_URL) for the React app
      # and the destination directory on the gh-pages branch.
      - name: Determine dynamic paths
        id: dynamic_paths
        run: |
          REPO_NAME="${{ github.event.repository.name }}"
          GITHUB_USERNAME="${{ github.repository_owner }}"

          # Handle both direct branch pushes and PRs
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            # For PRs, use the PR number as part of the branch slug
            BRANCH_SLUG="pr-${{ github.event.pull_request.number }}"
          else
            # For direct branch pushes, clean up the branch name
            BRANCH_SLUG=$(echo "${{ github.ref_name }}" | sed 's/\//-/g' | sed 's/[^a-zA-Z0-9-]//g' | tr '[:upper:]' '[:lower:]')
          fi

          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "PUBLIC_URL=https://$GITHUB_USERNAME.github.io/$REPO_NAME" >> $GITHUB_ENV
            echo "DEPLOY_DESTINATION_DIR=." >> $GITHUB_ENV
            echo "PREVIEW_URL=https://$GITHUB_USERNAME.github.io/$REPO_NAME" >> $GITHUB_ENV
          else
            echo "PUBLIC_URL=https://$GITHUB_USERNAME.github.io/$REPO_NAME/previews/$BRANCH_SLUG" >> $GITHUB_ENV
            echo "DEPLOY_DESTINATION_DIR=previews/$BRANCH_SLUG" >> $GITHUB_ENV
            echo "PREVIEW_URL=https://$GITHUB_USERNAME.github.io/$REPO_NAME/previews/$BRANCH_SLUG" >> $GITHUB_ENV
          fi

          echo "preview_url=${PREVIEW_URL}" >> "$GITHUB_OUTPUT"

      - name: Display calculated URLs and directories
        run: |
          echo "React App PUBLIC_URL: ${{ env.PUBLIC_URL }}"
          echo "Deployment Destination Directory: ${{ env.DEPLOY_DESTINATION_DIR }}"
          echo "Preview URL: ${{ steps.dynamic_paths.outputs.preview_url }}"


      - name: Install dependencies
        run: npm install # Install project dependencies defined in package.json

      # Build React app. The PUBLIC_URL environment variable will be picked up by Create React App.
      - name: Build React app
        run: npm run build
        env:
          PUBLIC_URL: ${{ env.PUBLIC_URL }} # Pass the determined PUBLIC_URL to CRA build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # Action specifically for deploying to gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication
          publish_dir: ./build # Directory containing the built application (output of npm run build)
          publish_branch: gh-pages # The branch to publish to
          destination_dir: ${{ env.DEPLOY_DESTINATION_DIR }} # Dynamically determined subdirectory
          force_orphan: true # This will orphan *only* the specific destination_dir, not the entire gh-pages branch.
          # If you want to keep other preview directories, 'force_orphan: true' with 'destination_dir' is correct.
          # If you want to keep other files *within* the specific destination_dir, you would need 'keep_files: true'
          # but 'force_orphan: true' overrides 'keep_files: true' for the target directory.
          # For a clean preview, force_orphan is generally desired for the specific preview directory.

      # (Optional) Add a step to comment the preview URL on Pull Requests
      # This part would typically be part of a separate job that runs only on pull_request events
      # but for demonstration, showing how to use the outputted URL.
      # This would require configuring your repo to allow workflow write access to PRs.
      - name: Comment Preview URL on Pull Request
        if: github.event_name == 'pull_request'
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const previewUrl = process.env.PREVIEW_URL;
            const commentBody = `
            🚀 **Preview Deployment Ready!** 🚀

            A preview of your changes has been deployed to:
            [${previewUrl}](${previewUrl})

            This preview will be automatically updated when you push new changes to this PR.
            `;

            // Find and update existing comment if it exists
            const { data: comments } = await github.rest.issues.listComments({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number
            });

            const existingComment = comments.find(comment =>
              comment.user.login === 'github-actions[bot]' &&
              comment.body.includes('Preview Deployment Ready!')
            );

            if (existingComment) {
              await github.rest.issues.updateComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                comment_id: existingComment.id,
                body: commentBody
              });
            } else {
              await github.rest.issues.createComment({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.issue.number,
                body: commentBody
              });
            }
        env:
          PREVIEW_URL: ${{ steps.dynamic_paths.outputs.preview_url }}
