name: Deploy to GitHub Pages (Per-Branch Previews)

on:
  push:
    branches:
      - main
      - '*' # Trigger on pushes to all branches
  pull_request:
    types: [opened, synchronize, reopened] # Trigger on PR creation, updates, and reopening
  schedule:
    - cron: '0 * * * *'  # Run every hour

# Explicitly grant permissions to the GITHUB_TOKEN for GitHub Pages deployment
permissions:
  contents: write # Needed to push to the gh-pages branch (for the build artifact)
  pages: write    # Needed for GitHub Pages deployment
  id-token: write # Needed for OpenID Connect (if using, generally good practice for GH Pages)

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Action to check out your repository code

      - name: Set up Node.js
        uses: actions/setup-node@v3 # Action to set up Node.js environment
        with:
          node-version: '18' # Specify Node.js version

      # Generate static data
      - name: Generate Static Data
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm install
          node scripts/generate-static.js

      # Build the React app with GitHub token
      - name: Build
        env:
          REACT_APP_GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          npm install
          npm run build

      # Deploy to GitHub Pages
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./build
          publish_branch: gh-pages
          commit_message: "Update site: ${{ github.event_name }}"
