# GitHub Actions workflow for deployment
# This file will be configured latername: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger on pushes to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use the latest Ubuntu runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v3 # Action to check out your repository code

      - name: Set up Node.js
        uses: actions/setup-node@v3 # Action to set up Node.js environment
        with:
          node-version: '18' # Specify Node.js version

      - name: Install dependencies
        run: npm install # Install project dependencies defined in package.json

      - name: Build React app
        run: npm run build # Run the build script to create optimized production build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3 # Action specifically for deploying to gh-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} # GitHub token for authentication
          publish_dir: ./build # Directory containing the built application (output of npm run build)
          publish_branch: gh-pages # The branch to publish to
          force_orphan: true # Overwrites the gh-pages branch each time, useful for SPAs
